export const TYPES = <const>{
  CHANGE_CITY: 'CHANGE_CITY',
  ON_SHOW_REQUEST: 'ON_SHOW_REQUEST',
  ON_SHOW_SUCCESS: 'ON_SHOW_SUCCESS',
  ON_SHOW_FAIL: 'ON_SHOW_FAIL',
  ADD_FAVORITE_CITY: 'ADD_FAVORITE_CITY',
};
